### ISSUE TITLE
Some Python tests failing

### ISSUE THREAD

**Issue by ima-10** [jeog/TDAmeritradeAPI#9]
**test_account_info_getters**
error response: 403
ABI :: InvalidRequest --> error code 103
- Failed 
Traceback (most recent call last):
  File "test.py", line 73, in test
    func(*args)
  File "test.py", line 520, in test_account_info_getters
    j = Get(g)
  File "test.py", line 58, in Get
    return getter.get()
  File "/.../python3.7/site-packages/tdma_api/get.py", line 228, in get
    r = clib.get_str('APIGetter_Get_ABI', self._obj)
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 200, in get_str
    call(fname, REF(obj), REF(c), REF(n))
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 162, in call
    raise CLibException(err)
tdma_api.clib.CLibException: TDMA_API_REQUEST_ERROR: forbidden: {
  "error" : "You don't have permission to access this resource."
}(response code =403) [error code: 103, line: 98, file: ../src/tdma_connect.cpp]

**test_preferences_getter**
error response: 403
ABI :: InvalidRequest --> error code 103
- Failed 
Traceback (most recent call last):
  File "test.py", line 73, in test
    func(*args)
  File "test.py", line 537, in test_preferences_getter
    j = Get(g)
  File "test.py", line 58, in Get
    return getter.get()
  File "/.../python3.7/site-packages/tdma_api/get.py", line 228, in get
    r = clib.get_str('APIGetter_Get_ABI', self._obj)
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 200, in get_str
    call(fname, REF(obj), REF(c), REF(n))
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 162, in call
    raise CLibException(err)
tdma_api.clib.CLibException: TDMA_API_REQUEST_ERROR: forbidden: {
  "error" : "You don't have permission to access this resource."
}(response code =403) [error code: 103, line: 98, file: ../src/tdma_connect.cpp]

**test_subscription_keys_getter**
error response: 400
ABI :: InvalidRequest --> error code 103
- Failed 
Traceback (most recent call last):
  File "test.py", line 73, in test
    func(*args)
  File "test.py", line 546, in test_subscription_keys_getter
    j = Get(g)
  File "test.py", line 58, in Get
    return getter.get()
  File "/.../python3.7/site-packages/tdma_api/get.py", line 228, in get
    r = clib.get_str('APIGetter_Get_ABI', self._obj)
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 200, in get_str
    call(fname, REF(obj), REF(c), REF(n))
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 162, in call
    raise CLibException(err)
tdma_api.clib.CLibException: TDMA_API_REQUEST_ERROR: validation problem: 
          {
        "error":"the query param being passed is not in the correct format"
                }
          (response code =400) [error code: 103, line: 133, file: ../src/tdma_connect.cpp]

**test_transaction_history_getters**
error response: 403
ABI :: InvalidRequest --> error code 103
- Failed 
Traceback (most recent call last):
  File "test.py", line 73, in test
    func(*args)
  File "test.py", line 564, in test_transaction_history_getters
    j = Get(g)
  File "test.py", line 58, in Get
    return getter.get()
  File "/.../python3.7/site-packages/tdma_api/get.py", line 228, in get
    r = clib.get_str('APIGetter_Get_ABI', self._obj)
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 200, in get_str
    call(fname, REF(obj), REF(c), REF(n))
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 162, in call
    raise CLibException(err)
tdma_api.clib.CLibException: TDMA_API_REQUEST_ERROR: forbidden: {
  "error" : "You don't have permission to access this resource."
}(response code =403) [error code: 103, line: 98, file: ../src/tdma_connect.cpp]

**test_order_getters**
error response: 403
ABI :: InvalidRequest --> error code 103
- Failed 
Traceback (most recent call last):
  File "test.py", line 73, in test
    func(*args)
  File "test.py", line 662, in test_order_getters
    tmp = Get(og)
  File "test.py", line 58, in Get
    return getter.get()
  File "/.../python3.7/site-packages/tdma_api/get.py", line 228, in get
    r = clib.get_str('APIGetter_Get_ABI', self._obj)
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 200, in get_str
    call(fname, REF(obj), REF(c), REF(n))
  File "/.../python3.7/site-packages/tdma_api/clib.py", line 162, in call
    raise CLibException(err)
tdma_api.clib.CLibException: TDMA_API_REQUEST_ERROR: forbidden: {
  "error" : "You don't have permission to access this resource."
}(response code =403) [error code: 103, line: 98, file: ../src/tdma_connect.cpp]

**Comment by jeog** [comment]
all of those have to do with a specific account number - make sure you're passing your account number/id (not your login) to the test script

also, if that works you may notice the streaming test fails towards the end because it can't use a particular subscription that tdma is not accepting. I just haven't updated the test yet.

**Comment by ima-10** [comment]
You're correct, I was passing my API login ID instead of my account ID. After fixing that the above tests passed. The test_streaming test failed at:

```
--CALLBACK----------------------------------------------------------------------
  Type      :: request_response
  Service   :: LEVELONE_FOREX           
  TimeStamp :: ...
  Msg/Data  :: {'code': 0, 'command ': 'SUBS', 'message': 'SUBS command succeeded', 'request_id': 9}
--------------------------------------------------------------------------------
- Failed 
Traceback (most recent call last):
  File "test.py", line 73, in test
    func(*args)
  File "test.py", line 1091, in test_streaming
    assert all(session.add_subscriptions(lofxs, lofos))
AssertionError
```

which is probably the failure you mentioned.
